spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loandesk
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"
loandesk:
  storage-root: ./data/kyc
