spring:
  application:
    name: LoanDesk
  datasource:
    url: jdbc:postgresql://localhost:5432/loandesk
    username: loandesk
    password: loandesk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    locations: classpath:db/migration

server:
  error:
    include-message: always

app:
  file-storage: ./data/kyc
