spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loandesk
    username: loandesk
    password: loandesk
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
