name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: loandesk
          POSTGRES_USER: loandesk
          POSTGRES_PASSWORD: loandesk
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build app
        run: mvn -pl app -am install -DskipTests
      - name: Start app
        run: mvn -pl app spring-boot:run -Dspring-boot.run.profiles=dev &
      - name: Wait for app
        run: sleep 20
      - name: Run Selenium tests
        run: mvn -pl tests test
